### PR TITLE
dropTables - createTables - updateTables - newDatas

### PR DESCRIPTION
**Pull request by selfup**
@JoshCheek @adamki 

Added `dropTables` functionality as well as updated DOCS.

Updating package version on next commit.

### CODE REVIEW

**Comment by selfup** [comment]
Ok version has been patched!

**Comment by selfup** [comment]
Going to add createTables as well

**Comment by selfup** [comment]
@JoshCheek @adamki 
- `createTables` has been added
- DOC/README updated
- Test: `getTables: four - dropTables: four - createTables: four` updated

**Comment by selfup** [comment]
Staying on same version 1.0.20 since this will become one update in general

**Comment by selfup** [comment]
Might have to merge my own branch. Need this new functionality for a new project I am working on.

**Comment by selfup** [comment]
New features - waiting for DOCS before I ask for the PR to be merged

**Comment by selfup** [comment]
@JoshCheek @adamki 

Was able to refactor getTables and dropTables. Any other method that I tried to refactor that depended on nested private methods would not work. So this is as far as I can go with private methods that take callbacks.

DOCS coming up next

**Comment by selfup** [comment]
@JoshCheek @adamki 

### Ready to be MERGED!
- Read through all the comments
- Need this for a project preferably tonight. 
- If you can merge that would be splendid!

**Comment by adamki** [comment]
@selfup sorry for delay.
- doc updates look great
- readme update looks great
- great job with the additional tests. 

things look ready to merge now.

**Pull request merged**
